### ISSUE TITLE
Latest update causes error, extension unusable

### ISSUE THREAD

**Issue by Scotty-Trees** [Leleat/extensions-in-system-menu#1]
Greetings,

First off, thank you for making this awesome, handy extension I've been using since it was created, it's very useful! 

With the latest update however, now the extension no longer works, I can't even turn it on within the Extensions application. Reloading gnome-shell doesn't seem to fix the issue either. Logging out and back in again doesn't fix anything either. I am currently using PopOS 20.04 which uses Gnome 3.36.8, and I'm using v2 of the extension. Perhaps maybe the update does work in Gnome 3.38, but at least in what I use in Gnome 3.36 it does no longer work sadly. 

Below are some screenshots to show that the extension is currently unusable with the latest update. Hope you can fix this issue!
![Screenshot from 2021-02-14 22-01-15](https://user-images.githubusercontent.com/45135187/107904152-9848cd80-6f10-11eb-9057-2420bc4bab70.png)
![Screenshot from 2021-02-14 22-00-42](https://user-images.githubusercontent.com/45135187/107904170-9bdc5480-6f10-11eb-9af1-04373c417b72.png)

**Comment by Leleat** [comment]
Hi, thanks for the report.

Sometimes EGO has troubles updating extensions (possibly because of settings?). One report on EGO makes me think that this is such a case.

>One need to Uninstall extension, restart GNOME SHell, adn then install the new version.
Looks like the extension does not disable properly.

Please try this first. 
1. Remove (and **not** just deactivate) the extension completely. 
2. Restart GNOME Shell.
3. install the extension again.

If that doesn't fix it. Then please repeat step 1 and 2. Then open a Terminal and run `journalctl -fo cat /usr/bin/gnome-shell`. Try to install the extension again and post the log from the Terminal here.

**Comment by Leleat** [comment]
Ah, nvm. I used some operators, which aren't supported on your system. I'll update the extension. The new extension should be up within a week.

**Comment by Scotty-Trees** [comment]
No worries, things happen and at least it seems like it was a super easy fix for ya. Thanks for the quick reply and feel free to ping me when the new update is out. I do check the Gnome extension website everyday or every other day, so I should notice an update when it arrives. Thanks again for your work, it's very useful :)

**Comment by Leleat** [comment]
Pushed an update to the master branch which supports GNOME 3.36 (tested in a PopOS 20.04 VM). Also submitted an updated version to EGO. Give it a week or so until it is reviewed by someone.
